<?php

namespace Tests\Unit\Http\Requests\Users;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\Users\UpdateUserRequest
 */
class UpdateUserRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Users\UpdateUserRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Users\UpdateUserRequest();
    }

    /**
     * @test
     */
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertEquals([], $actual);
    }

    // test cases...
}
