<?php

namespace Tests\Unit\Http\Requests\Chapters;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\Chapters\StoreChapterRequest
 */
class StoreChapterRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Chapters\StoreChapterRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Chapters\StoreChapterRequest();
    }

    /**
     * @test
     */
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'title' => [
                'required',
                'string',
            ],
            'timeline_id' => [
                'required',
                'integer',
                'exists:timelines,id',
            ],
            'cover' => [
                'sometimes',
                'image',
                'max:10240',
            ],
        ], $actual);
    }

    // test cases...
}
