<script context="module" lang="ts">
    import Base from '@/components/Layouts/Base.svelte'
    import Dashboard from '@/components/Layouts/Dashboard.svelte'
    export const layout = [Base, Dashboard]
</script>

<script lang="ts">
    import { fade } from 'svelte/transition'
    import { inertia, useForm } from '@inertiajs/svelte'
    import Breadcrumbs from '@/components/Chapters/Breadcrumbs.svelte'
    import bg from '@/assets/img/hero-bg.jpg'
    import Fa from 'svelte-fa'
    import Logo from '@/components/SVG/temp-logo.svg.svelte'
    import { faArrowLeft } from '@fortawesome/free-solid-svg-icons'
    import TipTap from '@/components/TipTap.svelte'
    import type { Editor } from '@tiptap/core'
    import Otto from '@/components/SVG/otto.svg.svelte'
    import { onMount } from 'svelte'
    import { start, done as finish } from '@/components/Loading.svelte'
    import { strToHtml } from '@/service/helpers'

    export let chapter: { data: App.Chapter }

    let enhance: Editor
    let original: Editor
    let loading: boolean = true
    let compare: boolean = false
    let language: string | null = null
    let initialText = ''

    const form = useForm({
        original: chapter.data.content,
        enhanced: '',
        use: null,
        status: chapter.data.status,
    })

    $form.use = 'enhanced'

    start()

    $: wordsOriginal =
        $form.original
            ?.replace(/(<([^>]+)>)/gi, '')
            .replace(/&nbsp;/gi, ' ')
            .trim()
            .split(/\s+/).length ?? 0
    $: wordsEnhanced =
        $form.enhanced
            ?.replace(/(<([^>]+)>)/gi, '')
            .replace(/&nbsp;/gi, ' ')
            .trim()
            .split(/\s+/).length ?? 0

    const controller = new AbortController()

    function submit(event: SubmitEvent) {
        $form
            .transform((data) => ({
                content: data[data.use],
                edit: null,
                status: event.submitter.dataset?.status ?? data.status,
                redirect: event.submitter.dataset?.redirect ?? null,
            }))
            .put(`/chapters/${chapter.data.id}`, {
                preserveScroll: true,
            })
    }

    async function translate(language = null) {
        if (import.meta.env.SSR) return

        const axios = (await import('axios')).default

        if (!language || loading) {
            $form.enhanced = initialText
            enhance?.commands.setContent(strToHtml($form.enhanced), false)
            return
        }

        loading = true
        enhance?.setOptions({ editable: false })

        axios
            .post('/translate', {
                text: $form.enhanced,
                options: {
                    target: language,
                },
            })
            .finally(() => {
                enhance?.setOptions({ editable: true })
                loading = false
            })
            .then((res) => {
                $form.enhanced = res.data.text
                enhance?.commands.setContent(strToHtml($form.enhanced), false)
            })
    }

    onMount(() => {
        original?.setOptions({ editable: false })
        enhance?.setOptions({ editable: false })

        fetch(`/chapters/${chapter.data.id}/enhance/stream`, { signal: controller.signal })
            .then((res) => res.body.pipeThrough(new TextDecoderStream()).getReader())
            .then((reader) =>
                reader.read().then(function pump({ done, value }) {
                    if (done) {
                        original?.setOptions({ editable: true })
                        enhance?.setOptions({ editable: true })
                        initialText = $form.enhanced
                        loading = false
                        return
                    }

                    $form.enhanced += value
                    enhance?.commands.setContent(strToHtml($form.enhanced), false)

                    if ($form.enhanced) {
                        finish()
                    }
                    return reader.read().then(pump)
                })
            )

        return () => {
            controller.abort()
        }
    })
</script>

<svelte:head>
    <title>{import.meta.env.VITE_APP_NAME} - {chapter.data.title}</title>
</svelte:head>

<Breadcrumbs step={3} />

<section
    class="container card relative m-4 mx-auto rounded-xl bg-cover bg-center md:p-12 lg:p-16"
    style="background-image: url({bg})"
    in:fade
>
    <div class="absolute inset-0 rounded-xl bg-gradient-to-r from-primary/80 to-primary/40" />
    <div class="card-body z-10 gap-8 text-primary-content">
        {#if !compare}
            <p class="flex items-center gap-8 text-2xl">
                <Logo class="h-16" />
                <span>This answer is generated by OTTO AI</span>
            </p>
        {/if}
        <h1 class="card-title font-serif text-4xl">
            {chapter.data.title}
        </h1>
    </div>
</section>

<form on:submit|preventDefault={submit} class="flex flex-col gap-8 p-4" in:fade>
    <section class="container mx-auto flex flex-col items-center justify-between gap-4 md:flex-row">
        <a href="/chapters/{chapter.data.id}/edit" class="btn btn-neutral rounded-full pl-0 font-normal" use:inertia>
            <span class="badge mask badge-accent mask-circle p-4"><Fa icon={faArrowLeft} /></span>
            Go Back
        </a>
        <div class="flex gap-4">
            {#if !compare && !loading}
                <button
                    type="button"
                    class="btn btn-primary btn-outline rounded-full"
                    on:click={() => {
                        compare = true
                        $form.use = null
                    }}
                >
                    Compare with My Writing
                </button>
            {/if}
            {#if $form.isDirty && $form.use && !loading}
                <button
                    type="submit"
                    class="btn btn-primary rounded-full"
                    data-status="published"
                    data-redirect="dashboard.chapters.finish"
                >
                    Complete & Finish this Chapter
                </button>
            {/if}
        </div>
        <div class="flex gap-4">
            {#if !loading}
                <div class="form-control flex-row gap-2">
                    <label class="label" for="language">
                        <span class="label-text">Output Language:</span>
                    </label>
                    <select
                        name="language"
                        id="language"
                        class="select select-primary"
                        bind:value={language}
                        on:change={() => translate(language)}
                    >
                        <option value={null}>Default</option>
                        <option value="en">English</option>
                        <option value="fr">French</option>
                    </select>
                </div>
            {/if}
            {#if $form.isDirty && $form.use && !loading}
                <button
                    type="submit"
                    class="btn btn-secondary rounded-full"
                    data-status="draft"
                    data-redirect="dashboard.stories.chapters.index"
                >
                    Save & Next
                </button>
            {/if}
        </div>
    </section>

    <main class:lg:grid-cols-2={compare} class="container mx-auto grid grid-cols-1 gap-8">
        <div class="form-control join join-vertical transition-all">
            <div class="alert alert-success flex items-center rounded-b-none">
                <span>You have shared {wordsEnhanced} words in this chapter</span>
                <span>|</span>
                <span>{Math.ceil(wordsEnhanced / 500)} pages</span>
            </div>
            <TipTap
                class="rounded-t-none border border-neutral-content/20 bg-neutral p-4 lg:text-lg"
                bind:editor={enhance}
                bind:content={$form.enhanced}
                placeholder="Write your story here..."
            >
                <div slot="top">
                    <h2
                        class="m-0 flex items-center justify-between gap-4 rounded-none border border-b-0 border-neutral-content/20 bg-neutral p-4 text-2xl font-normal text-primary md:text-3xl lg:text-4xl"
                    >
                        <span class="flex items-center gap-4"
                            ><Otto class="h-10" />
                            <span>Otto's <i>Enhance</i></span></span
                        >
                        {#if !loading}
                            <button
                                class="btn btn-primary btn-xs font-sans"
                                class:btn-outline={$form.use == 'enhanced'}
                                disabled={$form.use == 'enhanced'}
                                on:click|preventDefault={() => ($form.use = 'enhanced')}>Use OTTO Writing</button
                            >
                        {/if}
                    </h2>
                </div>
            </TipTap>
        </div>
        {#if compare}
            <div class="form-control join join-vertical transition-all">
                <div class="alert alert-info flex items-center rounded-b-none">
                    <span>You have shared {wordsOriginal} words in this chapter</span>
                    <span>|</span>
                    <span>{Math.ceil(wordsOriginal / 500)} pages</span>
                </div>
                <TipTap
                    class="rounded-t-none border border-neutral-content/20 bg-neutral p-4 lg:text-lg"
                    bind:editor={original}
                    bind:content={$form.original}
                    placeholder="Write your story here..."
                >
                    <h2
                        slot="top"
                        class="m-0 flex items-center justify-between gap-4 rounded-none border border-b-0 border-neutral-content/20 bg-neutral p-4 text-2xl md:text-3xl lg:text-4xl"
                    >
                        <span>Original Writing</span>
                        {#if !loading}
                            <button
                                class="btn btn-primary btn-xs font-sans"
                                class:btn-outline={$form.use == 'original'}
                                disabled={$form.use == 'original'}
                                on:click|preventDefault={() => ($form.use = 'original')}>Use Original Writing</button
                            >
                        {/if}
                    </h2>
                </TipTap>
            </div>
        {/if}
    </main>

    <section class="container mx-auto flex flex-col items-center justify-between gap-4 md:flex-row">
        <a href="/chapters/{chapter.data.id}/edit" class="btn btn-neutral rounded-full pl-0 font-normal" use:inertia>
            <span class="badge mask badge-accent mask-circle p-4"><Fa icon={faArrowLeft} /></span>
            Go Back
        </a>
        <div class="flex gap-4">
            {#if !compare && !loading}
                <button
                    type="button"
                    class="btn btn-primary btn-outline rounded-full"
                    on:click={() => {
                        compare = true
                        $form.use = null
                    }}
                >
                    Compare with My Writing
                </button>
            {/if}
            {#if $form.isDirty && $form.use && !loading}
                <button
                    type="submit"
                    class="btn btn-primary rounded-full"
                    data-status="published"
                    data-redirect="dashboard.chapters.finish"
                >
                    Complete & Finish this Chapter
                </button>
            {/if}
        </div>
        <div class="flex gap-4">
            {#if !loading}
                <div class="form-control flex-row gap-2">
                    <label class="label" for="language">
                        <span class="label-text">Output Language:</span>
                    </label>
                    <select
                        name="language"
                        id="language"
                        class="select select-primary"
                        bind:value={language}
                        on:change={() => translate(language)}
                    >
                        <option value={null}>Default</option>
                        <option value="en">English</option>
                        <option value="fr">French</option>
                    </select>
                </div>
            {/if}
            {#if $form.isDirty && $form.use && !loading}
                <button
                    type="submit"
                    class="btn btn-secondary rounded-full"
                    data-status="draft"
                    data-redirect="dashboard.stories.chapters.index"
                >
                    Save & Next
                </button>
            {/if}
        </div>
    </section>
</form>
