<?php

namespace Tests\Feature\Http\Controllers\Guests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Guests\AuthController
 */
class AuthControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function invoke_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $guest = \App\Models\Guest::factory()->create();

        $response = $this->get(route('login.guests', [$guest]));

        $response->assertRedirect(route('guests.chapters.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
