<?php

namespace Tests\Feature\Http\Controllers\Guests;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Guests\SetupController
 */
class SetupControllerTest extends TestCase
{
    /**
     * @test
     */
    public function post_setup_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('guests.setup.post'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('guests.chapters.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function setup_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('guests.setup'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
