<?php

namespace Tests\Unit\Http\Requests\Stories;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\Stories\UpdateStoryRequest
 */
class UpdateStoryRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Stories\UpdateStoryRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Stories\UpdateStoryRequest();
    }

    /**
     * @test
     */
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'title' => [
                'sometimes',
                'required',
                'string',
            ],
            'cover' => [
                'sometimes',
                'nullable',
                'image',
            ],
            'book_cover' => [
                'sometimes',
                'nullable',
                'image',
            ],
            'status' => [
                'sometimes',
                'required',
            ],
            'redirect' => [
                'sometimes',
                'nullable',
            ],
        ], $actual);
    }

    // test cases...
}
