<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SocialAuthController
 */
class SocialAuthControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function login_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('login.socialite', ['provider' => $provider]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function redirect_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->get(route('login.socialite.redirect', ['provider' => $provider]));

        $response->assertRedirect(intended(RouteServiceProvider::HOME));

        // TODO: perform additional assertions
    }

    // test cases...
}
