<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TranslateController
 */
class TranslateControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function __invoke_validates_with_a_form_request(): void
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\TranslateController::class,
            '__invoke',
            \App\Http\Requests\TranslateRequest::class
        );
    }

    /**
     * @test
     */
    public function invoke_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->actingAs($user)->post(route('dashboard.translate'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
