<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('book_cover_templates')
            ->where('id', 1)
            ->update([
                'fields' => '[{"key":"front","name":"Front Background","type":"image","group":"Front"},{"key":"title","name":"Title","type":"text","group":"Front"},{"key":"titleFont","name":"Title Font","type":"font","group":"Front","defaultValue":"ABCDiatype-Black-latin"},{"key":"titleSize","name":"Title Size","type":"number","group":"Front","defaultValue":27},{"key":"titleColor","name":"Title Color","type":"color","group":"Front","defaultValue":"#ffffff"},{"key":"author","name":"Author","type":"text","group":"Front"},{"key":"authorFont","name":"Author Font","type":"font","after":"author","group":"Front","defaultValue":"Truetypewritter"},{"key":"authorSize","name":"Author Size","type":"number","group":"Front","defaultValue":67},{"key":"authorColor","name":"Author Color","type":"color","group":"Front","defaultValue":"#4f4f4f"},{"key":"spine","name":"Spine Text","type":"text","group":"Spine"},{"key":"spineTextFont","name":"Spine Text Font","type":"font","group":"Spine","defaultValue":"Truetypewritter"},{"key":"spineTextSize","name":"Spine Text Size","type":"number","group":"Spine"},{"key":"spineBackgroundColor","name":"Spine Background Color","type":"color","group":"Spine","defaultValue":"#000000"},{"key":"spineTextColor","name":"Spine Text Color","type":"color","group":"Spine","defaultValue":"#ffffff"},{"key":"back","name":"Back Cover","type":"image","group":"Back"},{"key":"descriptionColor","name":"Description Color","type":"color","group":"Back","defaultValue":"#ffffff"},{"key":"description","name":"Description","type":"text","group":"Back"},{"key":"descriptionFont","name":"Description Text Font","type":"font","group":"Back","defaultValue":"ABCDiatype-Black-latin"},{"key":"descriptionTextSize","name":"Description Text Size","type":"number","group":"Back"},{"key":"descriptionTextBackground","name":"Description Text Background","type":"color","group":"Back","defaultValue":"#000000"}]'
            ]);

        DB::table('book_cover_templates')
            ->where('id', 2)
            ->update([
                'fields' => '[{"key":"front","name":"Front Background","type":"image","group":"Front"},{"key":"title","name":"Title","type":"text","group":"Front"},{"key":"titleFont","name":"Title Font","type":"font","group":"Front","defaultValue":"Truetypewritter"},{"key":"titleSize","name":"Title Size","type":"number","group":"Front","defaultValue":27},{"key":"titleColor","name":"Title Color","type":"color","group":"Front","defaultValue":"#ffffff"},{"key":"subtitle","name":"Subtitle","type":"text","group":"Front"},{"key":"subtitleFont","name":"Subtitle Font","type":"font","group":"Front","defaultValue":"merriweather-normal-300-latin"},{"key":"subtitleSize","name":"Subtitle Size","type":"number","group":"Front","defaultValue":27},{"key":"subtitleColor","name":"Subtitle Color","type":"color","group":"Front","defaultValue":"#ffffff"},{"key":"author","name":"Author","type":"text","group":"Front"},{"key":"authorFont","name":"Author Font","type":"font","after":"author","group":"Front","defaultValue":"merriweather-normal-300-latin"},{"key":"authorSize","name":"Author Size","type":"number","group":"Front","defaultValue":67},{"key":"authorColor","name":"Author Color","type":"color","group":"Front","defaultValue":"#595959"},{"key":"spine","name":"Spine Text","type":"text","group":"Spine"},{"key":"spineTextFont","name":"Spine Text Font","type":"font","group":"Spine","defaultValue":"merriweather-normal-300-latin"},{"key":"spineTextSize","name":"Spine Text Size","type":"number","group":"Spine"},{"key":"spineBackgroundColor","name":"Spine Background Color","type":"color","group":"Spine","defaultValue":"#000000"},{"key":"spineTextColor","name":"Spine Text Color","type":"color","group":"Spine","defaultValue":"#ffffff"},{"key":"back","name":"Back Cover","type":"image","group":"Back"},{"key":"descriptionColor","name":"Description Color","type":"color","group":"Back","defaultValue":"#000000"},{"key":"description","name":"Description","type":"text","group":"Back"},{"key":"descriptionFont","name":"Description Text Font","type":"font","group":"Back","defaultValue":"merriweather-normal-300-latin"},{"key":"descriptionTextSize","name":"Description Text Size","type":"number","group":"Back","defaultValue":""},{"key":"descriptionTextBackground","name":"Description Text Background","type":"color","group":"Back","defaultValue":"#ffffff"}]'
            ]);

        DB::table('book_cover_templates')
            ->where('id', 3)
            ->update([
                'fields' => '[{"key":"front","name":"Front Background","type":"image","group":"Front"},{"key":"title","name":"Title","type":"text","group":"Front"},{"key":"titleFont","name":"Title Font","type":"font","group":"Front","defaultValue":"merriweather-normal-300-latin"},{"key":"titleSize","name":"Title Size","type":"number","group":"Front","defaultValue":27},{"key":"titleColor","name":"Title Color","type":"color","group":"Front","defaultValue":"#000000"},{"key":"author","name":"Author","type":"text","group":"Front"},{"key":"authorFont","name":"Author Font","type":"font","after":"author","group":"Front","defaultValue":"merriweather-normal-300-latin"},{"key":"authorSize","name":"Author Size","type":"number","group":"Front","defaultValue":67},{"key":"authorColor","name":"Author Color","type":"color","group":"Front","defaultValue":"#5c5c5c"},{"key":"spine","name":"Spine Text","type":"text","group":"Spine"},{"key":"spineTextFont","name":"Spine Text Font","type":"font","group":"Spine","defaultValue":"merriweather-normal-300-latin"},{"key":"spineTextSize","name":"Spine Text Size","type":"number","group":"Spine"},{"key":"spineBackgroundColor","name":"Spine Background Color","type":"color","group":"Spine","defaultValue":"#000000"},{"key":"spineTextColor","name":"Spine Text Color","type":"color","group":"Spine","defaultValue":"#ffffff"},{"key":"back","name":"Back Cover","type":"image","group":"Back"},{"key":"descriptionColor","name":"Description Color","type":"color","group":"Back","defaultValue":"#ffffff"},{"key":"description","name":"Description","type":"text","group":"Back"},{"key":"descriptionFont","name":"Description Text Font","type":"font","group":"Back","defaultValue":"merriweather-normal-300-latin"},{"key":"descriptionTextSize","name":"Description Text Size","type":"number","group":"Back","defaultValue":27},{"key":"descriptionTextBackground","name":"Description Text Background","type":"color","group":"Back","defaultValue":"#000000"}]'
            ]);

        DB::table('book_cover_templates')
            ->where('id', 4)
            ->update([
                'fields' => '[{"key":"title","name":"Title","type":"text","group":"Front"},{"key":"titleFont","name":"Title Font","type":"font","group":"Front","defaultValue":"Garamond"},{"key":"titleSize","name":"Title Size","type":"number","group":"Front","defaultValue":27},{"key":"titleColor","name":"Title Color","type":"color","group":"Front","defaultValue":"#ffffff"},{"key":"subtitle","name":"Subtitle","type":"text","group":"Front"},{"key":"subtitleFont","name":"Subtitle Font","type":"font","group":"Front","defaultValue":"Garamond"},{"key":"subtitleSize","name":"Subtitle Size","type":"number","group":"Front","defaultValue":48},{"key":"subtitleColor","name":"Subtitle Color","type":"color","group":"Front","defaultValue":"#ffffff"},{"key":"author","name":"Author","type":"text","group":"Front"},{"key":"authorFont","name":"Author Font","type":"font","after":"author","group":"Front","defaultValue":"Garamond"},{"key":"authorSize","name":"Author Size","type":"number","group":"Front","defaultValue":67},{"key":"authorColor","name":"Author Color","type":"color","group":"Front","defaultValue":"#454545"},{"key":"front","name":"Front Background","type":"image","group":"Front"},{"key":"spineTextColor","name":"Spine Text Color","type":"color","group":"Spine","defaultValue":"#ffffff"},{"key":"spine","name":"Spine Text","type":"text","group":"Spine"},{"key":"spineTextFont","name":"Spine Text Font","type":"font","group":"Spine","defaultValue":"Garamond"},{"key":"spineTextSize","name":"Spine Text Size","type":"number","group":"Spine"},{"key":"spineBackgroundColor","name":"Spine Background Color","type":"color","group":"Spine","defaultValue":"#000000"},{"key":"back","name":"Back Cover","type":"image","group":"Back"},{"key":"descriptionColor","name":"Description Color","type":"color","group":"Back","defaultValue":"#000000"},{"key":"description","name":"Description","type":"text","group":"Back"},{"key":"descriptionFont","name":"Description Text Font","type":"font","group":"Back","defaultValue":"Truetypewritter"},{"key":"descriptionTextSize","name":"Description Text Size","type":"number","group":"Back","defaultValue":27},{"key":"descriptionTextBackground","name":"Description Text Background","type":"color","group":"Back","defaultValue":"#ffffff"}]'
            ]);

        DB::table('book_cover_templates')
            ->where('id', 5)
            ->update([
                'fields' => '[{"key":"front","name":"Front Background","type":"image","group":"Front"},{"key":"title","name":"Title","type":"text","group":"Front"},{"key":"titleFont","name":"Title Font","type":"font","group":"Front","defaultValue":"Baskerville 120"},{"key":"titleSize","name":"Title Size","type":"number","group":"Front","defaultValue":27},{"key":"titleColor","name":"Title Color","type":"color","group":"Front","defaultValue":"#000000"},{"key":"author","name":"Author","type":"text","group":"Front","defaultValue":""},{"key":"authorFont","name":"Author Font","type":"font","after":"author","group":"Front","defaultValue":"Baskerville 120"},{"key":"authorSize","name":"Author Size","type":"number","group":"Front","defaultValue":67},{"key":"authorColor","name":"Author Color","type":"color","group":"Front","defaultValue":"#363636"},{"key":"spineTextColor","name":"Spine Text Color","type":"color","group":"Spine","defaultValue":"#ffffff"},{"key":"spine","name":"Spine Text","type":"text","group":"Spine"},{"key":"spineTextFont","name":"Spine Text Font","type":"font","group":"Spine","defaultValue":"ABCDiatype-Black-latin"},{"key":"spineTextSize","name":"Spine Text Size","type":"number","group":"Spine"},{"key":"spineBackgroundColor","name":"Spine Background Color","type":"color","group":"Spine","defaultValue":"#000000"},{"key":"back","name":"Back Cover","type":"image","group":"Back"},{"key":"description","name":"Description","type":"text","group":"Back"},{"key":"descriptionFont","name":"Description Text Font","type":"font","group":"Back","defaultValue":"ABCDiatype-Black-latin"},{"key":"descriptionTextSize","name":"Description Text Size","type":"number","group":"Back","defaultValue":27},{"key":"descriptionTextBackground","name":"Description Text Background","type":"color","group":"Back","defaultValue":"#ffffff"},{"key":"descriptionColor","name":"Description Color","type":"color","group":"Back","defaultValue":"#000000"}]'
            ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
