name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: Install Composer Dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        args: -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Cache Node dependencies
      uses: actions/cache@v3
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
    - name: Build Front-end
      run: bun install && bun run build
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        ./vendor/bin/pint --test --format=txt
        php artisan test --coverage --min=70
        ./vendor/bin/phpstan --memory-limit=512M --no-progress
        npm run lint
